# 临时禁用的PR检查文件
# 此文件用于解决GitHub Actions语法错误问题

name: "PR Build Check (Disabled)"

# 不在任何条件下触发
on:
  workflow_dispatch:  # 只允许手动触发

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo "This workflow is disabled"
